name: Go
on: [push]
jobs:

  test:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.20.x' ]
    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

    - name: test
      run: |
        go vet ./...
        go test -shuffle on -cover -count 10 ./...
        go build
