name: Go
on: [push]
jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.24.6

      - name: Check out code into the Go module directory
        uses: actions/checkout@v5

      - name: test
        run: |
          go vet ./...
          go test -shuffle on -cover -count 10 ./...
          go build

      - name: bench
        run: |
          cd bench
          go test -bench=. -benchmem ./...
